[package]
name = "imagebumper"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1.86"
gitea-sdk = "0.5.0"
octocrab = "0.43.0"
tokio = { version = "1.43.0", features = ["fs", "macros", "rt-multi-thread"] }
url = "2.5.4"
