[package]
name = "atmosphere"
edition = "2021"

[dependencies]
tokio = { version = "1.43.0", features = ["fs", "macros", "rt-multi-thread"] }

[dev-dependencies]
rustainers = { path = "crates/rustainers" }

[workspace]
members = [ "crates/*" ]
