# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Deploy Cluster Secret Store for External Secrets
  run_once: true
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: external-secrets.io/v1
      kind: ClusterSecretStore
      kubeconfig: "{{ external_secrets_kubeconfig }}"
      metadata:
        name: "{{ external_secrets_cluster_secret_store_name }}"
        namespace: "{{ external_secrets_cluster_secret_store_namespace }}"
      spec: "{{ _external_secrets_cluster_secret_store_spec | combine(external_secrets_cluster_secret_store_spec, recursive=True) }}"

- name: Wait for Cluster Secret Store to be available
  run_once: true
  kubernetes.core.k8s_info:
    api_version: external-secrets.io/v1
    kind: ClusterSecretStore
    kubeconfig: "{{ external_secrets_kubeconfig }}"
    name: "{{ external_secrets_cluster_secret_store_name }}"
    namespace: "{{ external_secrets_cluster_secret_store_namespace }}"
    wait_sleep: 5
    wait_timeout: 90
    wait: true
    wait_condition:
      type: Ready
      status: true
