# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

valkey_helm_release_name: valkey
valkey_helm_chart_path: "../../charts/valkey/"
valkey_helm_chart_ref: /usr/local/src/valkey

# TLS
valkey_ca_certificate_name: "{{ valkey_helm_release_name }}-ca"
valkey_ca_certificate_common_name: valkey-ca
valkey_ca_certificate_secret_name: "{{ valkey_ca_certificate_name }}"
valkey_issuer_name: "{{ valkey_helm_release_name }}"
valkey_server_certificate_name: "{{ valkey_helm_release_name }}-server"
valkey_server_certificate_common_name: valkey
valkey_server_certificate_secret_name: "{{ valkey_server_certificate_name }}-certs"

valkey_helm_release_namespace: openstack
valkey_helm_values: {}
