# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- name: Prepare host for OVN BGP agent
  hosts: all
  tasks:
    - name: Install VRF module
      become: true
      ansible.builtin.package:
        name: linux-modules-extra-{{ ansible_kernel }}
