# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

_vault_spec:
  size: 3
  image: "{{ atmosphere_images['vault'] }}"
  nodeSelector:
    openstack-control-plane: enabled
  serviceAccount: vault
  serviceType: ClusterIP
  # NOTE(fitbeard): We do external ingress configuration
  ingress: null
  volumeClaimTemplates:
    - metadata:
        name: vault-raft
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
  volumes:
    - name: vault-raft
      persistentVolumeClaim:
        claimName: vault-raft
  volumeMounts:
    - name: vault-raft
      mountPath: /vault/data
  caNamespaces:
    - "*"
  unsealConfig:
    options:
      preFlightChecks: true
      storeRootToken: true
      secretShares: 5
      secretThreshold: 3
    kubernetes:
      secretNamespace: "{{ vault_namespace }}"
  config:
    storage:
      raft:
        path: /vault/data
    listener:
      tcp:
        address: 0.0.0.0:8200
        tls_cert_file: /vault/tls/server.crt
        tls_key_file: /vault/tls/server.key
    api_addr: "https://vault.{{ vault_namespace }}:8200"
    cluster_addr: "https://${.Env.POD_NAME}:8201"
    disable_mlock: true
    ui: true
    plugin_directory: /vault/plugins
    service_registration:
      kubernetes: {}
    telemetry:
      unauthenticated_metrics_access: true
  statsdDisabled: true
  serviceRegistrationEnabled: true
  externalConfig: {}
  secretInitsConfig:
    - name: VAULT_LOG_LEVEL
      value: "{{ vault_log_level }}"
