# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

collections:
  - name: atmosphere.common
    src: https://github.com/vexxhost/atmosphere.common
    version: add-vault-operator-role
  - ansible.netcommon:
      version: 1.2.0
  - ansible.posix:
      version: 1.3.0
  - ansible.utils:
      version: ">=2.9.0"
  - community.crypto:
      version: 2.2.3
  - community.hashi_vault:
      version: ">=6.2.0"
  - community.general:
      version: 7.3.0
  - community.mysql:
      version: 3.6.0
  - kubernetes.core:
      version: 2.4.0
  - openstack.cloud:
      version: ">=2.0.0"
  - vexxhost.ceph:
      version: ">=3.1.2"
  - vexxhost.kubernetes:
      version: ">=2.0.1"
