# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

_external_secrets_cluster_secret_store_spec:
  provider:
    vault:
      server: "{{ external_secrets_cluster_secret_store_vault_address | default('https://vault.vault-operator-system:8200') }}"
      path: "{{ atmosphere_vault_mount_point }}"
      version: v2
      # TODO(fitbeard): Make CA configurable
      caProvider:
        type: Secret
        namespace: "{{ external_secrets_cluster_secret_store_namespace }}"
        name: vault-tls
        key: ca.crt
      auth:
        kubernetes:
          mountPath: "{{ external_secrets_cluster_secret_store_vault_auth_mount_path | default('kubernetes/local') }}"
          role: "{{ external_secrets_cluster_secret_store_vault_auth_role | default('external-secrets-cluster-secret-store') }}"
          serviceAccountRef:
            name: external-secrets
            namespace: "{{ external_secrets_cluster_secret_store_namespace }}"
