# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

# NOTE(fitbeard): We need Cert Manager installed before secret components
- name: Deploy Cert Manager
  hosts: controllers
  become: true
  roles:
    - role: cert_manager
      tags:
        - cert-manager

- name: Deploy Secrets Infrastructure
  import_playbook: vexxhost.atmosphere.secrets

- name: Deploy Infrastructure
  hosts: controllers
  become: true
  roles:
    - role: cluster_issuer
      tags:
        - cluster-issuer

    - role: ingress_nginx
      tags:
        - ingress-nginx

    - role: rabbitmq_cluster_operator
      tags:
        - rabbitmq-cluster-operator

    - role: percona_xtradb_cluster_operator
      tags:
        - percona-xtradb-cluster-operator

    - role: percona_xtradb_cluster
      tags:
        - percona-xtradb-cluster

    - role: valkey
      tags:
        - valkey

    - role: keycloak
      tags:
        - keycloak

    - role: keepalived
      tags:
        - keepalived
