# Copyright (c) 2025 VEXXHOST, Inc.
# SPDX-License-Identifier: Apache-2.0

- hosts: "{{ target | default('all') }}"
  become: true
  roles:
    - role: defaults
    - role: sysctl
      tags:
        - sysctl
    - role: ethtool
      tags:
        - ethtool
     # NOTE(fitbeard) networkd-dispatcher is not available for EL distros
      when: ansible_facts['os_family'] in ['Debian']
  post_tasks:
    - name: Set a fact with the "atmosphere_images" for other plays
      ansible.builtin.set_fact:
        atmosphere_images: "{{ atmosphere_images }}"
      tags:
        - always

- hosts: "{{ target | default('all') }}"
  become: true
  gather_facts: false
  tasks:
    - name: Install PIP
      ansible.builtin.package:
        name: python3-pip

    # (rico) there is dependency isuse with pyopenssl and cryptography before 22.1.0
    # This make sure we have consist dependency between them.
    - name: Upgrade pyopenssl in pip
      ansible.builtin.pip:
        name:
          - pyopenssl>=22.1.0
        extra_args: --upgrade

- import_playbook: vexxhost.kubernetes.site
  vars:
    keepalived_image: "{{ atmosphere_images['keepalived'] }}"
    keepalived_vrid: "{{ kubernetes_keepalived_vrid }}"
    keepalived_interface: "{{ kubernetes_keepalived_interface }}"
    keepalived_vip: "{{ kubernetes_keepalived_vip }}"
    haproxy_image: "{{ atmosphere_images['haproxy'] }}"
    containerd_pause_image: "{{ atmosphere_images['pause'] }}"
    kubernetes_image_repository: "{{ atmosphere_images['kube_apiserver'] | vexxhost.kubernetes.docker_image('prefix') }}"
    kubernetes_version: 1.28.13
    cilium_node_image: "{{ atmosphere_images['cilium_node'] }}"
    cilium_operator_image: "{{ atmosphere_images['cilium_operator'] }}"
    kube_vip_image: "{{ atmosphere_images['kube_vip'] }}"

- hosts: "{{ target | default('all') }}"
  become: true
  roles:
    - role: vexxhost.atmosphere.kubernetes_node_labels
      tags:
        - kubernetes-node-labels

# NOTE(mnaser): Add task to uninstall "unattended-upgrades" to avoid system
#               upgrades during the deployment
- hosts: "{{ target | default('all') }}"
  become: true
  gather_facts: false
  tasks:
    - name: Uninstall unattended-upgrades
      ansible.builtin.package:
        name: unattended-upgrades
        state: absent

- ansible.builtin.import_playbook: atmosphere.common.metrics_server
  vars:
    target: controllers
    metrics_server_image: "{{ atmosphere_images['metrics_server'] }}"
    metrics_server_helm_values:
      nodeSelector:
        openstack-control-plane: enabled
