name: backports

on:
  pull_request_target:
    types: [closed]
  issue_comment:
    types: [created]

permissions:
  contents: write
  pull-requests: write

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    # NOTE(mnaser): https://github.com/korthout/backport-action?tab=readme-ov-file#trigger-using-a-comment
    if: >
      (
        github.event_name == 'pull_request_target' &&
        github.event.pull_request.merged
      ) || (
        github.event_name == 'issue_comment' &&
        github.event.issue.pull_request &&
        github.event.comment.user.id != 105816074 &&
        startsWith(github.event.comment.body, '/backport')
      )
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
      - uses: korthout/backport-action@436145e922f9561fc5ea157ff406f21af2d6b363 # v3.2.0
        with:
          github_token: ${{ secrets.VEXXHOST_BOT_PAT }}
          copy_labels_pattern: skip-release-notes
